### ISSUE TITLE
Reference requirements

### ISSUE THREAD

**Issue by huagliu** [HenKlei/geodesic-shooting#17]
Could you provide some references for the function ''integrate_backward_adjoint_Jacobi_field''？

**Comment by HenKlei** [comment]
Hi @huagliu, thank you for showing interest in my work.

So for the aforementioned function, I oriented myself on the paper "Finite-Dimensional Lie Algebras for Fast Diffeomorphic Image Registration" by Miaomiao Zhang and Thomas Fletcher. In chapter 4.2 of that paper you can find the equations for the adjoint Jacobi fields. In the function `integrate_backward_adjoint_Jacobi_field`, I perform a simple integration of that equation backwards in time to obtain the gradient of the energy function with respect to the initial velocity field.

I hope this helps. Feel free to contact me (preferably via email, I would like to use Github issues mainly for problems directly related to the code), if there are any questions left.

**Comment by HenKlei** [comment]
@huagliu, did this answer all of your questions or is there something left?

Btw, I have a new implementation for landmark matching based on reproducing kernel Hilbert spaces in the `feature/landmarks` branch. Feel free to check it out!

**Comment by huagliu** [comment]
Thanks! Your answer perfectly solved my problem. 

The 2D landmark matching example is very impressive. Looking forward to your wonderful work in the future.
